### ISSUE TITLE
Google Team Drive Support?

### ISSUE THREAD

**Issue by RiverbayChris** [CloudRail/cloudrail-si-ios-sdk#19]
Does CloudRail support Google's Team Drive feature?

**Comment by fel-cesar** [comment]
Hi @RiverbayChris ,
We currently don't support Google's Team Drive feature due to the current pathfinding structure, though that can be a future feature in our schedule. Also depending on the demand for it, we can consider it if you will use it for a long time. You can contact us at support@cloudrail.com for a talk regarding this "new feature".
