### ISSUE TITLE
Creating Custom InputStream crashes the app

### ISSUE THREAD

**Issue by mohitnandwani** [CloudRail/cloudrail-si-ios-sdk#25]
I'm trying to create a progress bar for uploading files but it crashes the app. I tried using this code for Input Stream: https://blog.cloudrail.com/progress-indication-dropbox-google-drive-upload-download/

I somewhat converted the code to swift. So here is the swift version: 

```
import UIKit

protocol UploadProgressDelegate: class {
    func didUploadBytes(bytes: Int)
}

class CustomInputStream: InputStream {
    
    var inputStream: InputStream?
    weak var uploadProgressDelegate: UploadProgressDelegate?
    var offset = 0
    
    convenience init(inputStream: InputStream, delegate: UploadProgressDelegate) {
        self.init()
        self.inputStream = inputStream
        self.uploadProgressDelegate = delegate
        self.offset = 0
    }
    
    override func read(_ buffer: UnsafeMutablePointer<UInt8>, maxLength len: Int) -> Int {
        let res = inputStream?.read(buffer, maxLength: len)
        offset += res ?? 0
        uploadProgressDelegate?.didUploadBytes(bytes: offset)
        return res ?? 0
    }
    
}

```

And whenever I try to upload something I get this error: 

> Thread 1: EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0)

I tried to customise the code in Example app (in CloudStorgeLogic File) 
From:

```
static func uploadFileToPath(cloudStorage: CloudStorageProtocol,
                          path: String,
                          inputStream: InputStream,
                          size: Int) -> Bool
```

To:

```
static func uploadFileToPath(cloudStorage: CloudStorageProtocol,
                          path: String,
                          inputStream: CustomStream,
                          size: Int) -> Bool
```

But still no luck. Any help would be appreciated.
Thanks.

**Comment by mohitnandwani** [comment]
Any update on this?

**Comment by fel-cesar** [comment]
Hello @mohitnandwani,

You have to create your own customized stream only for **download progress** If I got it right you want to simply have a feedback on the upload progress from our method. I realized you tried to make a subclass of the InputStream for such purpose. Although that is a comprehensible mistake that will be mitigated in future updates of the framework and the blog post you just mentioned. The **CustomStream** in the blog post is actually a **already implemented** class that is bundled together with the CloudRail framework, so you don't need to create a new custom stream for upload, just use the one we are providing (since we already took care of all the override methods). 

Example of a File Upload with a progress callback (THE CLASS MUST IMPLEMENT THE **CRUploadProgressDelegate**):

``` swift
func uploadFile() -> Void {
    let dropbox = Dropbox.init(clientId: "CLIENT_ID", clientSecret: "CLIENT_SECRET")

    do {
      //get an image from url - Could be from any source, but for test purposes lets download from external website and then upload it to CloudStorage root.
      let data:Data = try Data.init(contentsOf: URL(string: "https://upload.wikimedia.org/wikipedia/commons/e/e6/Clocktower_Panorama_20080622_20mb.jpg")!)

      //Creating an instance of CustomStream from an InputStream using the data aquired (could be any source)
      let customStream:CustomStream = CustomStream.init(stream: InputStream.init(data: data))
      customStream.uploadProgressDelegate = self;

      //Upload the image using the CustomStream
      try dropbox.uploadFileToPath("/TEST_UPLOAD.jpg", stream: customStream, size: data.count, overwrite: true)
      print("CRLOG: FINISHED UPLOAD")

    } catch  {
      print("CRLOG: EXCEPTION THROWN:[\(error)]")
    }
  }

  //MARK: Delegate methods
  func onBytesWritten(bytesWritten: CLong) {
    print("CRLOG: \(Float(Float(bytesWritten)/data.count))")
  }
```
